from collections.abc import Iterator, Sequence
from typing import Any

class KModel:
    def __init__(self, repo_id: str = ...) -> None: ...
    def to(self, device: str) -> KModel: ...
    def eval(self) -> KModel: ...
    def __call__(self, ps: Any, ref_s: Any, speed: float) -> Any: ...

class KPipeline:
    def __init__(
        self,
        lang_code: str,
        model: bool = ...,
        repo_id: str = ...,
    ) -> None: ...
    def load_voice(self, voice: str) -> Sequence[Any]: ...
    def __call__(
        self, text: str, voice: str, speed: float
    ) -> Iterator[tuple[Any, Any, Any]]: ...
